### ISSUE TITLE
Postinstall Error on yarn install

### ISSUE THREAD

**Issue by hsiraaj** [stevenliuyi/covid19#13]
error D:\XXXX\XXXX\XXXX\covid19\node_modules\postinstall-postinstall: Command failed
.
Exit code: 1
Command: node ./run.js
Arguments:
Directory: D:\XXXX\XXXX\XXXX\covid19\node_modules\postinstall-postinstall
Output:
No such package ;

  File not found: D:/XXXX/XXXX/XXXX/covid19/node_modules/;/package.json
error Command failed with exit code 1.
child_process.js:669
    throw err;
    ^

Error: Command failed: yarn run postinstall
No such package ;

  File not found: D:/XXXX/XXXX/XXXX/covid19/node_modules/;/package.json
error Command failed with exit code 1.

    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at Object.<anonymous> (D:\xampp\htdocs\covid\node_modules\postinstall-postin
stall\run.js:14:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

**Comment by stevenliuyi** [comment]
Can you check if the `postinstall-postinstall` package is correctly installed?
