### ISSUE TITLE
yarn install error- some sub folders in data are missing

### ISSUE THREAD

**Issue by abhinav-gurung** [stevenliuyi/covid19#28]
while doing yarn install I am getting this error. Its trying to open file  ‘data/dxy-data/csv/DXYArea.csv’ and file  'data/jhu-data/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv'

but its not there. any one has similar issue?

[o] Wrote public/maps/gadm36_CHN_1.json
[merge-layers] Warning: Fields [GID_1, NAME_1, NL_NAME_1, GID_2, NAME_2, VARNAME_2, NL_NAME_2, TYPE_2, ENGTYPE_2, CC_2, HASC_2] are missing from one or more layers
[o] Wrote public/maps/gadm36_CHN_2.json
tac: failed to open ‘data/dxy-data/csv/DXYArea.csv’ for reading: No such file or directory
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'data/jhu-data/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at generateData (/home/abhinavkumar.gurung@cloud.statcan.ca/Applications/p22/covid19/src/scripts/data_processing_world.js:113:19)
    at Object.<anonymous> (/home/abhinavkumar.gurung@cloud.statcan.ca/Applications/p22/covid19/src/scripts/data_processing_world.js:249:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
error Command failed with exit code 1.

    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at Object.<anonymous> (/home/abhinavkumar.gurung@cloud.statcan.ca/Applications/p22/covid19/node_modules/postinstall-postinstall/run.js:15:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by estebaniglesias** [comment]
Hi! Did you clone with --recursive?
git clone --recursive https://github.com/stevenliuyi/covid19.git

**Comment by abhinav-gurung** [comment]
i missed to do that. can i pull the submodules in my branch after?

**Comment by estebaniglesias** [comment]
I don't know, in fact, I think you might found that looking on google

**Comment by abhinav-gurung** [comment]
i did that using git submodule --init.  isnt it supposed to pull maps as well?

**Comment by estebaniglesias** [comment]
I think this might help you"
https://github.com/stevenliuyi/covid19/issues/23#issuecomment-610552735
