### ISSUE TITLE
How install this code 

### ISSUE THREAD

**Issue by Theblood** [stevenliuyi/covid19#5]
Help Me?

**Comment by stevenliuyi** [comment]
You can use "yarn install" to install the project. Also note that you need to include the submodules when you clone the repo using "--recurse-submodules" or "--recursive".

**Comment by arielcavadia1** [comment]
Hi, why install project in server to cpanel linux?

**Comment by nndnha** [comment]
`yarn install` error:
```
[o] Wrote public/maps/gadm36_PRT_2.json
assert.js:339
    throw err;
    ^

AssertionError [ERR_ASSERTION]: undefined is not a valid count!
    at forEach (/tmp/covid19/scripts/missing_data_fix.js:40:13)
    at Array.forEach (<anonymous>)
    at fillMissingData (/tmp/covid19/scripts/missing_data_fix.js:20:54)
    at Object.keys.filter.forEach (/tmp/covid19/scripts/missing_data_fix.js:55:13)
    at Array.forEach (<anonymous>)
    at fillMissingData (/tmp/covid19/scripts/missing_data_fix.js:54:10)
    at Object.<anonymous> (/tmp/covid19/scripts/missing_data_fix.js:59:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```
